# Generated by Django 4.0.4 on 2022-05-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220507_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numLevel',
            field=models.IntegerField(blank=True, choices=[(0, 'Owner'), (1, 'Admin'), (2, 'Manager'), (3, 'Member')], null=True, verbose_name='User Level*'),
        ),
    ]
