# Generated by Django 4.0.4 on 2022-06-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_numlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='numLevel',
            field=models.IntegerField(null=True),
        ),
    ]
