# Generated by Django 4.0.4 on 2022-05-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreezerDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('deviceId', models.IntegerField(null=True)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FreezerWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('warehouseId', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('maxTempLimit', models.FloatField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('emailRecipents', models.CharField(max_length=200, null=True)),
                ('smsRecipents', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreezersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freezers.freezerdevice')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freezers.freezerwarehouse')),
            ],
        ),
        migrations.AddField(
            model_name='freezerdevice',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='freezers.freezerwarehouse'),
        ),
    ]
