# Generated by Django 3.1.7 on 2022-05-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('key', models.CharField(max_length=200, null=True)),
                ('createdAt', models.DateField(auto_now=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('dataFrequency', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('Temperature+Humidity', 'Temperature+Humidity'), ('NPK+Temperature+Humidity', 'NPK+Temperature+Humidity'), ('Hydroponics', 'Hydroponics'), ('Custom', 'Custom')], default='Dormant', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='weatherStationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNumber', models.CharField(max_length=200, null=True)),
                ('timeStamp', models.DateTimeField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('pressure', models.CharField(max_length=20, null=True)),
                ('local_temperature', models.CharField(max_length=20, null=True)),
                ('local_humidity', models.CharField(max_length=20, null=True)),
                ('local_pressure', models.CharField(max_length=20, null=True)),
                ('solar_radiation', models.CharField(max_length=20, null=True)),
                ('sun_rise', models.CharField(max_length=20, null=True)),
                ('sun_set', models.CharField(max_length=20, null=True)),
                ('sun_duration', models.CharField(max_length=20, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('wind_speed', models.CharField(max_length=20, null=True)),
                ('air_quality', models.CharField(max_length=20, null=True)),
                ('battery', models.CharField(max_length=20, null=True)),
                ('humidity', models.CharField(max_length=20, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.device')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('warehouseId', models.CharField(max_length=200, null=True)),
                ('long', models.CharField(blank=True, max_length=200, null=True)),
                ('latt', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNumber', models.CharField(max_length=200, null=True)),
                ('timeStamp', models.DateTimeField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('soilMoisture', models.CharField(max_length=200, null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('ppm', models.IntegerField(null=True)),
                ('ph', models.IntegerField(null=True)),
                ('waterTemp', models.CharField(max_length=200, null=True)),
                ('energyConsumption', models.CharField(max_length=200, null=True)),
                ('waterLevel', models.CharField(max_length=200, null=True)),
                ('n', models.CharField(max_length=200, null=True)),
                ('p', models.CharField(max_length=200, null=True)),
                ('k', models.CharField(max_length=200, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.device')),
            ],
        ),
        migrations.CreateModel(
            name='hydroponicSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srNumber', models.CharField(max_length=200, null=True)),
                ('timeStamp', models.DateTimeField(null=True)),
                ('water_temperature', models.IntegerField(null=True)),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('ppm', models.CharField(max_length=50, null=True)),
                ('ph_level', models.CharField(max_length=50, null=True)),
                ('atmospheric_temp', models.CharField(max_length=50, null=True)),
                ('humidity', models.CharField(max_length=50, null=True)),
                ('water_level', models.CharField(blank=True, max_length=50)),
                ('energy_consumption', models.CharField(blank=True, max_length=50)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.warehouse'),
        ),
    ]
