# Generated by Django 3.1.7 on 2022-05-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezerWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('warehouseId', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SmartRack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('createdAt', models.DateField(auto_now=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('Temperature+Humidity', 'Temperature+Humidity'), ('NPK+Temperature+Humidity', 'NPK+Temperature+Humidity'), ('Hydroponics', 'Hydroponics'), ('Custom', 'Custom')], default='Dormant', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='hydroponicsensor',
            name='device',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='latt',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='long',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weatherstationdata',
            name='device',
        ),
        migrations.DeleteModel(
            name='device',
        ),
        migrations.DeleteModel(
            name='hydroponicSensor',
        ),
        migrations.AddField(
            model_name='smartrack',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.warehouse'),
        ),
    ]
