# Generated by Django 4.0.4 on 2022-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20220507_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezerwarehouse',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='freezerwarehouse',
            name='warehouseId',
            field=models.IntegerField(null=True),
        ),
    ]
