# Generated by Django 4.0.4 on 2022-05-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_freezerwarehouse_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('deviceId', models.IntegerField(null=True)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.freezerwarehouse')),
            ],
        ),
    ]
