# Generated by Django 4.0.4 on 2022-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_freezersdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezerdevice',
            name='maxTempLimit',
            field=models.FloatField(null=True),
        ),
    ]
