# Generated by Django 4.0.4 on 2022-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_freezerdevice_maxtemplimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezersdata',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
