# Generated by Django 4.0.4 on 2022-05-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_freezersdata_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freezersdata',
            old_name='temperature',
            new_name='temp',
        ),
    ]
