# Generated by Django 4.0.4 on 2022-05-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_rename_temperature_freezersdata_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezersdata',
            name='log',
            field=models.FloatField(null=True),
        ),
    ]
