# Generated by Django 4.0.4 on 2022-05-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_freezersdata_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezersdata',
            name='log',
        ),
        migrations.AddField(
            model_name='freezersdata',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
    ]
