# Generated by Django 4.0.4 on 2022-05-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_freezerwarehouse_emailrecpents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freezerwarehouse',
            old_name='emailRecpents',
            new_name='emailRecipents',
        ),
    ]
