# Generated by Django 4.0.4 on 2022-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_freezerwarehouse_smsrecipents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartrack',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='smartrack',
            name='warehouse',
            field=models.ManyToManyField(null=True, to='administrator.warehouse', verbose_name='warehouse'),
        ),
    ]
