# Generated by Django 4.0.4 on 2022-05-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_remove_smartrack_warehouse_smartrack_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezerdevice',
            name='maxTempLimit',
        ),
        migrations.AddField(
            model_name='freezerwarehouse',
            name='maxTempLimit',
            field=models.FloatField(null=True),
        ),
    ]
