# Generated by Django 4.0.4 on 2022-05-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_remove_freezerdevice_maxtemplimit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezersdata',
            name='isActive',
        ),
        migrations.AddField(
            model_name='freezerdevice',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
    ]
