# Generated by Django 4.0.4 on 2022-05-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_remove_freezersdata_isactive_freezerdevice_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseId', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='sensorData',
        ),
        migrations.RemoveField(
            model_name='smartrack',
            name='user',
        ),
        migrations.RemoveField(
            model_name='smartrack',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='weatherStationData',
        ),
        migrations.AlterField(
            model_name='freezerdevice',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SmartRack',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
