# Generated by Django 4.0.4 on 2022-05-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_rackwarehouse_delete_sensordata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezersdata',
            name='device',
        ),
        migrations.RemoveField(
            model_name='freezersdata',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='FreezerDevice',
        ),
        migrations.DeleteModel(
            name='FreezersData',
        ),
        migrations.DeleteModel(
            name='FreezerWarehouse',
        ),
    ]
