# Generated by Django 4.0.4 on 2022-05-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_remove_freezersdata_device_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RackWarehouse',
        ),
    ]
