# Generated by Django 4.0.4 on 2022-06-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='serverState',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment', models.CharField(max_length=10, null=True)),
                ('boxstate', models.CharField(max_length=10, null=True)),
                ('code', models.CharField(max_length=10, null=True)),
                ('livestatedisplay', models.CharField(max_length=10, null=True)),
                ('livestaterelay', models.CharField(max_length=10, null=True)),
                ('livesatefeedback', models.CharField(max_length=10, null=True)),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartracks.warehouse')),
            ],
        ),
    ]
